application/book/forms.py
# from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, Form
from wtforms.validators import Length, NumberRange, DataRequired


class SearchForm(Form):
    keyword = StringField(validators=[Length(min=1, max=30), DataRequired()])
    page = IntegerField(default=1, validators=[NumberRange(min=1, max=99)])

application/drift/forms.py
from wtforms import StringField, Form
from wtforms.validators import Length, DataRequired, Regexp


class DriftForm(Form):
    recipient_name = StringField(
        '收件人姓名', validators=[Length(min=2, max=20, message='收件人姓名长度必须在2-20之间'), DataRequired()])
    mobile = StringField('手机号', validators=[Regexp('^1[0-9]{10}$', 0, '请输入正确的手机号'), DataRequired()])
    message = StringField('留言')
    address = StringField(
        '邮寄地址', validators=[Length(min=10, max=70, message='地址还不到10个字？请尽量填写详细地址'), DataRequired()])

application/__init__.py
from flask import Flask, render_template
from flask_mail import Mail
from flask_migrate import Migrate

from .models import db, login_manager


mail = Mail()
migrate = Migrate()


def not_found(e):
    return render_template('404.html'), e.code


def create_app():
    app = Flask(__name__)
    app.config.from_object('application.security')
    app.config.from_object('application.settings')

    register_blueprint(app)

    db.init_app(app)
    mail.init_app(app)
    migrate.init_app(app, db)

    login_manager.init_app(app)
    login_manager.login_view = 'auth.login'
    login_manager.login_message = '请登录或者注册帐号'

    with app.app_context():
        db.create_all(app=app)

    app.errorhandler(404)(not_found)
    return app


def register_blueprint(app):
    from .book import book_bp
    from .auth import auth_bp
    from .trade import trade_bp
    from .drift import drift_bp
    app.register_blueprint(book_bp)
    app.register_blueprint(auth_bp)
    app.register_blueprint(trade_bp)
    app.register_blueprint(drift_bp)

application/book/__init__.py
from flask import Blueprint

book_bp = Blueprint('book', __name__)


from . import views

application/book/views.py
from flask import request, render_template, flash, redirect, url_for
from flask_login import current_user

from . import book_bp as book
from .forms import SearchForm
from ..spider.fisher_book import FisherBook
from .viewmodels import BookCollection
from ..models import Gift, Wish
from ..trade.viewmodels import Trades


@book.route('/index')
def index():
    gifts = Gift.recent()
    books = [gift.book for gift in gifts]
    return render_template('book/index.html', books=books)


@book.route('/book/<isbn>')
def book_detail(isbn):
    has_in_gifts = False
    has_in_wishes = False
    fisher_book = FisherBook()
    fisher_book.search(isbn)
    if not fisher_book.first:
        flash(f'未找到目标书籍:{isbn}')
        return redirect(url_for('book.index'))

    if current_user.is_authenticated:
        if Gift.get_book_goods(fisher_book.first.id, current_user.id):
            has_in_gifts = True
        if Wish.get_book_goods(fisher_book.first.id, current_user.id):
            has_in_wishes = True

    gifts = Trades(Gift.get_book_goods(fisher_book.first.id))
    wishes = Trades(Wish.get_book_goods(fisher_book.first.id))

    return render_template('book/book_detail.html', book=fisher_book.first,
                           has_in_wishes=has_in_wishes, has_in_gifts=has_in_gifts, wishes=wishes, gifts=gifts)


@book.route('/book/search/')
def search():
    form = SearchForm(request.args)
    books = BookCollection()
    if form.validate():
        page = form.page.data
        keyword = form.keyword.data
        fisher_book = FisherBook()
        from_db = fisher_book.search(keyword, page=page)
        books.handle_data(fisher_book, keyword, from_db)

    return render_template('book/search_result.html', books=books, wishes=[], gifts=[])

application/drift/__init__.py
from flask import Blueprint


drift_bp = Blueprint('drift', __name__)


from . import views

application/drift/views.py
from flask import render_template, redirect, request, url_for, flash
from flask_login import login_required, current_user
from sqlalchemy import or_, desc

from application.utils.email import send_mail
from . import drift_bp as drift
from .forms import DriftForm
from ..models import db, Gift, Drift, User, Wish
from ..utils.enums import PendingStatus
from .viewmodels import DriftCollection


@drift.route('/drift/<gid>', methods=['GET', 'POST'])
@login_required
def send_drift(gid):
    form = DriftForm(request.form)
    gift = Gift.query.get_or_404(gid)

    if gift.is_yourself_gift(current_user.id):
        flash('你不能想自己请求礼物')
        return redirect(url_for('book.book_detail', isbn=gift.isbn))

    if not current_user.can_send_drift():
        return render_template('drift/not_enough_beans.html', beans=current_user.beans)

    if (request.method == 'POST') and form.validate():
        save_drift(form, gift)
        send_mail(gift.user.email, '有人向你请求一本书', 'email/get_gift.html',
                  wisher=current_user, gift=gift)
        return redirect(url_for('drift.pending'))

    return render_template('drift/drift.html', presenter=gift.user.summary, user_beans=current_user.beans, form=form)


@drift.route('/drift/<int:did>/mailed')
@login_required
def mailed_drift(did):
    drift_obj = Drift.query.filter_by(presenter_id=current_user.id, id=did).first_or_404()
    gift = Gift.query.get_or_404(drift_obj.gift_id)
    wish = Wish.query.filter_by(isbn=Drift.book_isbn, uid=Drift.requester_id, launched=False).first_or_404()
    with db.auto_commit():
        drift_obj.pending = PendingStatus.Success
        current_user.beans += 1
        gift.launched = True
        wish.launched = True

    return redirect(url_for('drift.pending'))


@drift.route('/drift/<int:did>//reject_drift')
@login_required
def reject_drift(did):
    drift_obj = Drift.query.filter_by(presenter_id=current_user.id, id=did).first_or_404()
    with db.auto_commit():
        drift_obj.pending = PendingStatus.Reject
        User.query.get_or_404(drift_obj.requester_id).beans += 1

    return redirect(url_for('drift.pending'))


@drift.route('/drift/<int:did>/redraw')
@login_required
def redraw_drift(did):
    drift_obj = Drift.query.filter_by(requester_id=current_user.id, id=did).first_or_404()
    with db.auto_commit():
        drift_obj.pending = PendingStatus.Redraw
        current_user.beans += 1

    return redirect(url_for('drift.pending'))


@drift.route('/pending')
@login_required
def pending():
    drifts = Drift.query.filter(
        or_(Drift.requester_id==current_user.id, Drift.presenter_id==current_user.id)
    ).order_by(desc(Drift.create_time)).all()

    return render_template('drift/pending.html', drifts=DriftCollection(drifts, current_user.id).data)


@drift.route('/drift/<int:wid>/satisfy')
@login_required
def satisfy_wish(wid):
    wish = Wish.query.get_or_404(wid)
    gift = Gift.query.filter_by(uid=current_user.id, isbn=wish.isbn).first()
    if not gift:
        flash('你还没上传此书，请点击"加入到赠送清单"添加此书。添加前，请确保自己可以赠送此书')
    else:
        send_mail(wish.user.email, '有人想赠送你一本书', 'email/satisfy_wish.html', wish=wish, gift=gift)
        flash('已向他/她发送了一封邮件，如果他/她愿意接受你的赠送，你将收到一个鱼漂')

    return redirect(url_for('book.book_detail', isbn=wish.isbn))


def save_drift(form, gift):
    drift_obj = Drift()
    drift_obj.recipient_name = form.recipient_name.data
    drift_obj.address = form.address.data
    drift_obj.mobile = form.mobile.data
    drift_obj.message = form.message.data
    drift_obj.book_isbn = gift.isbn
    drift_obj.book_title = gift.book.title
    drift_obj.book_author = gift.book.author
    drift_obj.book_img = gift.book.image
    drift_obj.requester_id = current_user.id
    drift_obj.requester_nickname = current_user.nickname
    drift_obj.presenter_id = gift.user.id
    drift_obj.gift_id = gift.id
    drift_obj.presenter_nickname = gift.user.nickname
    drift_obj.pending = PendingStatus.Waiting
    with db.auto_commit():
        current_user.beans -= 1
        db.session.add(drift_obj)

application/trade/__init__.py
from flask import Blueprint


trade_bp = Blueprint('trade', __name__)

from . import views

application/trade/views.py
from datetime import datetime
from functools import wraps

from flask import redirect, render_template, url_for, flash, current_app, abort
from flask_login import current_user, login_required

from ..utils.enums import PendingStatus
from . import trade_bp as trade
from ..models import db, Gift, Wish, Drift
from ..spider.fisher_book import FisherBook
from .viewmodels import MyTrades


def book_check(func):
    @wraps(func)
    def decorator(isbn, *args, **kwargs):
        book = FisherBook()
        book.search(isbn)
        if not book.first:
            abort(404)
        else:
            return func(isbn, *args, **kwargs, bid=book.first.id)

    return decorator


@trade.route('/my_gifts')
@login_required
def my_gifts():
    gifts = Gift.get_user_goods(current_user.id)
    isbn_lst = [gift.isbn for gift in gifts]
    goods_count = Gift.get_goods_counts(Wish, isbn_lst)
    my_trades = MyTrades(gifts, goods_count)
    return render_template('trade/my_gifts.html', gifts=my_trades.trades)


@trade.route('/my_wishes')
@login_required
def my_wishes():
    wishes = Wish.get_user_goods(current_user.id)
    isbn_lst = [wish.isbn for wish in wishes]
    goods_count = Wish.get_goods_counts(Gift, isbn_lst)
    my_trades = MyTrades(wishes, goods_count)
    return render_template('trade/my_wishes.html', wishes=my_trades.trades)


@trade.route('/gifts/book/<isbn>')
@login_required
@book_check
def save_to_gifts(isbn, bid=-1):
    if Wish.query.filter_by(uid=current_user.id, bid=bid, launched=False).first():
        flash('此书籍已经在你的心愿清单中')
    else:
        gift = Gift.query.filter_by(use_base=True, bid=bid, uid=current_user.id, launched=False).first()

        if gift and gift.status:
            redraw_gift(bid)
        elif gift and (not gift.status):
            gift.restore()
        else:
            Gift.add(isbn, bid, current_user.id)

    return redirect(url_for('book.book_detail', isbn=isbn))


@trade.route('/wish/book/<isbn>')
@login_required
@book_check
def save_to_wishes(isbn, bid=-1):
    if Gift.query.filter_by(uid=current_user.id, bid=bid, launched=False).first():
        flash('此书籍已经在你的赠送清单中')
    else:
        wish = Wish.query.filter_by(use_base=True, bid=bid, uid=current_user.id, launched=False).first()

        if wish and wish.status:
            wish.delete()
        elif wish and (not wish.status):
            wish.restore()
        else:
            Wish.add(isbn, bid, current_user.id)

    return redirect(url_for('book.book_detail', isbn=isbn))


@trade.route('/gifts/redraw/<isbn>')
@login_required
@book_check
def redraw_from_gifts(isbn, bid=-1):
    redraw_gift(bid)

    return redirect(url_for('trade.my_gifts'))


@trade.route('/wishes/redraw/<isbn>')
@login_required
@book_check
def redraw_from_wishes(isbn, bid=-1):
    wish = Wish.query.filter_by(bid=bid).first_or_404()
    wish.delete()

    return redirect(url_for('trade.my_wishes'))


def redraw_gift(bid):
    gift = Gift.query.filter_by(bid=bid).first_or_404()
    drift = Drift.query.filter_by(gift_id=gift.id, pending=PendingStatus.Waiting).first()
    if drift is not None:
        flash('这个礼物正处于交易状态，请先前往鱼漂完成交易')
        return
    gift.delete()

application/templates/trade/gifts.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
   <link rel="stylesheet" href="{{ url_for('static', filename='css/gifts.css')}}">
{% endblock %}
{% block content %}
    <div class="row module-title shadow-bottom">
        <div class="col-md-2">
            <span class='description-title'>最近上传</span>
        </div>
        <hr/>
    </div>
    <div class="row">
        {% for book in recent.books %}
            <a href="{{ url_for('book.book_detail', isbn=book.isbn) }}" class="">
                <div class="col-md-5 col-padding">
                    <div class="col-md-8">
                        <img class="book-img-base" src="{{ book.image }}">
                    </div>
                    <div class="col-md-9 flex-vertical">
                            <span id="title"
                                  style="font-size: 16px;margin-bottom: 15px">{{ book.title }}</span>
                        <span id="author">{{ book.author }}</span>
                        <span id="publisher">{{ book.publisher }}</span>
                        <span id="price">{{ book.price }}</span>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

application/templates/trade/my_gifts.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
    {{ super() }}
    <div class="row flex-vertical-center">
        <div style="margin-top:20px;" class="col-md-6">
            <span class="sub-title">我想赠送的书籍  共  {{ gifts | length }} 本</span>
            <hr>
        </div>
    </div>
    {% for gift in gifts %}
        <div class="row">
            <a href="{{ url_for('book.book_detail', isbn=gift.book.isbn) }}" class="">
                <div style="margin-bottom:30px;" class="col-md-9 col-padding">
                    <div class="col-md-2">
                        <img class="book-img-small shadow" src="{{ gift.book.image }}">
                    </div>
                    <div style="margin-top:6px;" class="col-md-6 flex-vertical">
                            <span id="title"
                                  class="book-middle-title">{{ gift.book.title }}</span>
                        <div style="margin-top:6px;"
                             class="flex-vertical description-font">
                            <span id="author">{{ gift.book.author }}</span>
                            <span id="publisher">{{ gift.book.publisher }}</span>
                            <span id="price">{{ gift.book.price }}</span>
                            <span id="isbn">{{ gift.book.isbn }}</span>
                        </div>
                        <a class="link-normal"
                           href="{{ url_for('trade.redraw_from_gifts', isbn=gift.isbn) }}">
                            撤销
                        </a>
                    </div>
                    <div class="col-md-3 flex-vertical">
                        {% if gift.trades_count %}
                            <a href="{{ url_for('book.book_detail', isbn=gift.book.isbn) }}">
                                <span class="bg-info">{{ gift.trades_count }}人想要</span>

                            </a>
                        {% endif %}
                    </div>
                </div>
            </a>
        </div>
    {% endfor %}
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename="js/util.js") }}"></script>
    <script src="{{ url_for('static', filename='js/search_result.js') }}"></script>
{% endblock %}

application/templates/trade/my_wish.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
    {{ super() }}
    <div class="row flex-vertical-center">
        <div style="margin-top:20px;" class="col-md-6">
            <span class="sub-title">我想要的书籍  共  {{ wishes | length }} 本</span>
            <hr>
        </div>
    </div>
    {% for wish in wishes %}
        <div class="row">
            <a href="{{ url_for('book.book_detail', isbn=wish.book.isbn) }}" class="">
                <div style="margin-bottom:30px;" class="col-md-9 col-padding">
                    <div class="col-md-2">
                        <img class="book-img-small shadow" src="{{ wish.book.image }}">
                    </div>
                    <div style="margin-top:6px;" class="col-md-6 flex-vertical">
                            <span id="title"
                                  class="book-middle-title">{{ wish.book.title }}</span>
                        <div style="margin-top:6px;"
                             class="flex-vertical description-font">
                            <span id="author">{{ wish.book.author }}</span>
                            <span id="publisher">{{ wish.book.publisher }}</span>
                            <span id="price">{{ wish.book.price }}</span>
                            <span id="isbn">{{ wish.book.isbn }}</span>
                        </div>
                        <a class="link-normal"
                           href="{{ url_for('trade.redraw_from_wish', isbn=wish.book.isbn) }}">
                            撤销
                        </a>
                    </div>
                    <div class="col-md-3 flex-vertical">
                        {% if wish.trades_count %}
                            <a href="{{ url_for('book.book_detail', isbn=wish.book.isbn) }}">
                                <span class="bg-info">{{ wish.trades_count }}人赠送</span>
                            </a>
                        {% endif %}
                    </div>
                </div>
            </a>
        </div>
    {% endfor %}

{% endblock %}
{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename="js/util.js") }}"></script>
{% endblock %}

application/templates/trade/my_wishes.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
    {{ super() }}
    <div class="row flex-vertical-center">
        <div style="margin-top:20px;" class="col-md-6">
            <span class="sub-title">我想要的书籍  共  {{ wishes | length }} 本</span>
            <hr>
        </div>
    </div>
    {% for wish in wishes %}
        <div class="row">
            <a href="{{ url_for('book.book_detail', isbn=wish.book.isbn) }}" class="">
                <div style="margin-bottom:30px;" class="col-md-9 col-padding">
                    <div class="col-md-2">
                        <img class="book-img-small shadow" src="{{ wish.book.image }}">
                    </div>
                    <div style="margin-top:6px;" class="col-md-6 flex-vertical">
                            <span id="title"
                                  class="book-middle-title">{{ wish.book.title }}</span>
                        <div style="margin-top:6px;"
                             class="flex-vertical description-font">
                            <span id="author">{{ wish.book.author }}</span>
                            <span id="publisher">{{ wish.book.publisher }}</span>
                            <span id="price">{{ wish.book.price }}</span>
                            <span id="isbn">{{ wish.book.isbn }}</span>
                        </div>
                        <a class="link-normal"
                           href="{{ url_for('trade.redraw_from_wishes', isbn=wish.book.isbn) }}">
                            撤销
                        </a>
                    </div>
                    <div class="col-md-3 flex-vertical">
                        {% if wish.trades_count %}
                            <a href="{{ url_for('book.book_detail', isbn=wish.book.isbn) }}">
                                <span class="bg-info">{{ wish.trades_count }}人赠送</span>
                            </a>
                        {% endif %}
                    </div>
                </div>
            </a>
        </div>
    {% endfor %}

{% endblock %}
{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename="js/util.js") }}"></script>
{% endblock %}